/**********************************************************/
/* Automatically generated by './mkconfig': do note edit! */
/**********************************************************/
#define LGL_OS "Linux norbert-T420s 3.8.0-38-generic x86_64"
#define LGL_COMPILED "Mon Mar 17 14:26:08 CET 2014"
#define LGL_RELEASED "Sat Oct 13 14:05:26 CEST 2012"
#define LGL_VERSION "ala"
#define LGL_ID "b02aa1a04343558c4252b5f4a723be021964f652"
