# checksmac.sh, Norbert Manthey, 2015
#
# rerun call that has been generated by check-smac
#
# usage: ./checksmac.sh <solver-pcs-file> <solver-dir-name> <number-of-fix-attempts>
#
# example call: ./recheck-config.sh instance configs
#
# Assumes ./riss binary/link in the current directory
# 

file=$1
shift

echo "./riss -checkModel -config= `python ./mapCSSCparams.py $*` $file "

gdb --args ./riss -checkModel -quiet -config= `python ./mapCSSCparams.py $*` $file 
exit $?
