# Makefile for riss
# Copyright (c) 2012-2015, Norbert Manthey

EXEC      = risslibcheck

DEPDIR    = mtl utils core simp 

# extern control whether coprocessor should be integrated
DEPDIR    += $(CPDEPEND)

CFLAGS    += $(INCFLAGS)
LFLAGS    += $(INLDFLAGS)


include $(MROOT)/mtl/template.mk
