# Makefile for riss
# Copyright (c) 2012-2013, Norbert Manthey

EXEC      = riss3g

DEPDIR    = mtl utils 

# extern control whether coprocessor should be integrated
DEPDIR    += $(CPDEPEND)

CFLAGS    += $(INCFLAGS)
LFLAGS    += $(INLDFLAGS)


include $(MROOT)/mtl/template.mk
