
EXEC      = glucose

DEPDIR    = mtl utils 

# extern control whether coprocessor should be integrated
DEPDIR    += $(CPDEPEND)

CFLAGS    += $(INCFLAGS)
LFLAGS    += $(INLDFLAGS)


include $(MROOT)/mtl/template.mk
