# Makefile for dratcheck based on riss data strcutures
# Copyright (c) 2012-2015, Norbert Manthey

EXEC      = dratcheck

DEPDIR    = mtl utils 

CFLAGS    += $(INCFLAGS)
LFLAGS    += $(INLDFLAGS)

include $(MROOT)/mtl/template.mk
