# Makefile for CNF classifier
# Copyright (c) 2012-2013, Norbert Manthey

EXEC      = classifier
DEPDIR    = mtl utils core coprocessor-src

CFLAGS    += $(INCFLAGS)
LFLAGS    += $(INLDFLAGS)

include $(MROOT)/mtl/template.mk
